name: web3dart_walletconnect
description: Implementing a web3dart connection with walletconnect
version: 0.0.1
homepage: https://github.com/inveker/web3dart_walletconnect

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  walletconnect_dart: ^0.0.11
  web3dart: ^2.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
